# Generated by Django 4.2.8 on 2024-01-17 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=128, null=True)),
                ('login', models.CharField(max_length=6000, null=True)),
                ('password', models.CharField(max_length=6000, null=True)),
                ('date_registration', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'user_registration',
                'managed': False,
            },
        ),
    ]
